### PR TITLE
Update fasta_build_add_kraken2_bracken subworkflow 

### LINKED ISSUE #1: Add Bracken database build
### Description of feature

Will require Kraken2 build as a upstream step, and just need extra read length parameter

### PR DESCRIPTION
**Pull request by alxndrdiaz**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/createtaxdb/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/createtaxdb _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

Fixes #1

### CODE REVIEW

**Comment by alxndrdiaz** [comment]
`nextflow run . -profile test` fails with the following error: 

```
ERROR ~ ERROR: Validation of pipeline parameters failed!

 -- Check '.nextflow.log' file for details
The following invalid input values have been detected:

* Missing required parameter: --outdir
```
So this needs parameter needs to be updated.

**Comment by alxndrdiaz** [comment]
When running  `nextflow run . -profile test --outdir=/home/nf-core/tests,` the following error is raised: 

```
Pipeline completed with errors-
ERROR ~ Error executing process > 'NFCORE_CREATETAXDB:CREATETAXDB:KAIJU_MKFMI (database)'

Caused by:
  Process `NFCORE_CREATETAXDB:CREATETAXDB:KAIJU_MKFMI (database)` terminated with an error exit status (127)

Command executed:

  kaiju-mkbwt \
       \
      -n 2 \
      -o database \
      database.faa
  kaiju-mkfmi database
  
  cat <<-END_VERSIONS > versions.yml
  "NFCORE_CREATETAXDB:CREATETAXDB:KAIJU_MKFMI":
      kaiju: $(echo $( kaiju -h 2>&1 | sed -n 1p | sed 's/^.*Kaiju //' ))
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 4: kaiju-mkbwt: command not found
```
Should all nf-test related bugs should be fixed before merging this branch?

**Comment by jfy133** [comment]
Is that because you're missing singularity/conda or docker in your command ?

**Comment by alxndrdiaz** [comment]
> Is that because you're missing singularity/conda or docker in your command ?

I confirm this was the issue, locally the test is successful, using: `nextflow run . -profile test,docker --outdir=/home/nf-core/tests`: 
```
executor >  local (12)
[d4/4e3f34] process > NFCORE_CREATETAXDB:CREATETAXDB:GUNZIP_DNA (haemophilus_influenzae.fna.gz)               [100%] 1 of 1 ✔
[37/3571b3] process > NFCORE_CREATETAXDB:CREATETAXDB:CAT_CAT_DNA (database)                                   [100%] 1 of 1 ✔
[f4/67a5d8] process > NFCORE_CREATETAXDB:CREATETAXDB:PIGZ_COMPRESS_AA (database)                              [100%] 1 of 1 ✔
[18/1e4589] process > NFCORE_CREATETAXDB:CREATETAXDB:CAT_CAT_AA (database)                                    [100%] 1 of 1 ✔
[f9/3a8697] process > NFCORE_CREATETAXDB:CREATETAXDB:CENTRIFUGE_BUILD (database)                              [100%] 1 of 1 ✔
[46/be5c7e] process > NFCORE_CREATETAXDB:CREATETAXDB:DIAMOND_MAKEDB (database)                                [100%] 1 of 1 ✔
[5c/f5a2d0] process > NFCORE_CREATETAXDB:CREATETAXDB:KAIJU_MKFMI (database)                                   [100%] 1 of 1 ✔
[ac/c4ba22] process > NFCORE_CREATETAXDB:CREATETAXDB:FASTA_BUILD_ADD_KRAKEN2_BRACKEN:KRAKEN2_ADD (database)   [100%] 1 of 1 ✔
[d5/5549eb] process > NFCORE_CREATETAXDB:CREATETAXDB:FASTA_BUILD_ADD_KRAKEN2_BRACKEN:KRAKEN2_BUILD (database) [100%] 1 of 1 ✔
[0d/b54c3c] process > NFCORE_CREATETAXDB:CREATETAXDB:UNZIP (megan-nucl-Feb2022.db.zip)                        [100%] 1 of 1 ✔
[17/52f9c1] process > NFCORE_CREATETAXDB:CREATETAXDB:MALT_BUILD (1)                                           [100%] 1 of 1 ✔
[5a/18e49e] process > NFCORE_CREATETAXDB:CREATETAXDB:MULTIQC                                                  [100%] 1 of 1 ✔
-[nf-core/createtaxdb] Pipeline completed successfully-
Completed at: 21-May-2024 10:25:38
Duration    : 2m 24s
CPU hours   : (a few seconds)
Succeeded   : 12
```

**Comment by alxndrdiaz** [comment]
Error related to failed check (nf-core CI / nf-test ...):

```
Found 1 files in test directory.

Test pipeline: NFCORE_CREATETAXDB

java.lang.RuntimeException: Path /home/runner/work/createtaxdb/createtaxdb/.nf-test/tests/aa06ef15b1d2bac6ab77b23519901408/output/kraken2/db/hash.k2d not found.
  Test [aa06ef15] 'test_profile' FAILED (128.576s)

  Assertion failed: 
  
  1 of 6 assertions failed
  
  Nextflow stdout:
  
  Nextflow stderr: 
```

**Comment by jfy133** [comment]
OK I will investigate!

**Review by jfy133 — COMMENTED** [review]
@alxndrdiaz I went full whack as I got annoyed at the other PR I'm working on :laughing: 

But thanks for putting the foundations in!

Even if it sounds a bit weird, could you 'review' your own PR to check my changes are OK?

I used here: https://hackmd.io/psKX3BvyRZepqZmV1VjvpA as my checklist

Note that there is no metromap yet, not usage docs (I will do this at the end prior release)

**Comment by alxndrdiaz** [comment]
> @alxndrdiaz I went full whack as I got annoyed at the other PR I'm working on 😆
> 
> But thanks for putting the foundations in!
> 
> Even if it sounds a bit weird, could you 'review' your own PR to check my changes are OK?
> 
> I used here: https://hackmd.io/psKX3BvyRZepqZmV1VjvpA as my checklist
> 
> Note that there is no metromap yet, not usage docs (I will do this at the end prior release)

@jfy133 After a (very fast) review I confirm all changes were made as described in the checklist. Also all three tests (with docker, singularity and conda) work as expected [Nextflow version 24.04.1]. There is only a warning that is raised when running any of the tests (it seems it does not affect the results):  

```
WARN: Access to undefined parameter monochromeLogs -- Initialise it to a default value eg. params.monochromeLogs = some_value
```

Also the conda test raises a warning which does not affect the results as well: 

```
WARN: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  There is a problem with your Conda configuration!

  You will need to set-up the conda-forge and bioconda channels correctly.
  Please refer to https://bioconda.github.io/
  The observed channel order is 
  [bioconda, defaults, conda-forge]
  but the following channel order is required:
  [conda-forge, bioconda, defaults]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by jfy133** [comment]
Thanks for the notes on the two warnings!

The conda one generally isn't important. The monochrome log thing is from the template and will fix that in a different PR.

Thanks for the review of my half of the PR! Will merge now

**Review by jfy133 — APPROVED** [review]

**Pull request merged**
